[build-system]
requires = ["setuptools>=61.0.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "coolth"
description = "Control Midea (and associated brands) smart air conditioners over the local network or the Midea cloud. This controls: Artic King, Cooper & Hunter, Midea Air, NetHome Plus, SmartHome/MSmartHome, Toshiba AC NA, and 美的美居."
readme = "README.md"
authors = [
  {name = "Andy Hawkins", email = "andy@a904guy.com"},
]
requires-python = ">=3.10"
license = "MIT"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
  "Topic :: Home Automation"
]
dependencies = [
  "httpx",
  "pycryptodome"
]
dynamic = ["version"]

[project.optional-dependencies]
yaml = ["pyyaml"]

[project.urls]
Repository = "https://github.com/a904guy/coolth-ac-controller"
Issues = "https://github.com/a904guy/coolth-ac-controller/issues"

[project.scripts]
coolth = "coolth.cli:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["."]
include = ["coolth", "coolth.*"]


[tool.setuptools_scm]